name: cars-trends-staging
region: sfo3
spec:
  name: cars-trends-staging
  region: sfo3
  services:
    - name: backend
      image:
        registry_type: GHCR
        repository: jesushzv/cars-trends-tool/backend
        tag: latest
      http_port: 8000
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /api
      envs:
        - key: SECRET_KEY
          scope: RUN_AND_BUILD_TIME
          value: "__TO_FILL_AFTER_GENERATION__"
        - key: DATABASE_URL
          scope: RUN_TIME
          value: "__TO_FILL_AFTER_DB_CREATED__"
        - key: LISTING_RETENTION_DAYS
          scope: RUN_TIME
          value: "90"
        - key: SNAPSHOT_RETENTION_DAYS
          scope: RUN_TIME
          value: "180"
        - key: TIMEZONE
          scope: RUN_TIME
          value: "America/Tijuana"
        - key: ENABLE_SCHEDULER
          scope: RUN_TIME
          value: "false"
        - key: FACEBOOK_COOKIES_JSON
          scope: RUN_TIME
          value: ""
      health_check:
        http_path: /health

    - name: frontend
      image:
        registry_type: GHCR
        repository: jesushzv/cars-trends-tool/frontend
        tag: latest
      http_port: 80
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /


