name: cars-trends-staging
region: sfo3
services:
  - name: backend
    git:
      repo_clone_url: https://github.com/jesushzv/cars-trends-tool.git
      branch: main
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: "__TO_FILL_AFTER_GENERATION__"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "__TO_FILL_AFTER_DB_CREATED__"
      - key: LISTING_RETENTION_DAYS
        scope: RUN_TIME
        value: "90"
      - key: SNAPSHOT_RETENTION_DAYS
        scope: RUN_TIME
        value: "180"
      - key: TIMEZONE
        scope: RUN_TIME
        value: "America/Tijuana"
      - key: ENABLE_SCHEDULER
        scope: RUN_TIME
        value: "false"
      - key: FACEBOOK_COOKIES_JSON
        scope: RUN_AND_BUILD_TIME
        value: ""
    health_check:
      http_path: /health

static_sites:
  - name: frontend
    git:
      repo_clone_url: https://github.com/jesushzv/cars-trends-tool.git
      branch: main
    source_dir: frontend
    output_dir: .
    routes:
      - path: /



